baseURL = 'https://www.entscheidung-zur-heilung.de/'
languageCode = 'de-de'
title = 'Von der Entscheidung zur Heilung'
subtitle = 'Podcast über Abtreibungserfahrungen'
author = 'Thea Amanda Kupler'
theme = 'castanet'
defaultContentLanguage = "de"
buildFuture = true

# Pagination settings
[pagination]
pagerSize = 9

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[permalinks]
about = "/:contentbasename/"
episode = "/:contentbasename/"

# Navigation Menu
[[menu.main]]
name = "Startseite"
url = "/"
weight = 1

[[menu.main]]
name = "Über mich"
url = "/ueber-mich/"
weight = 2

[[menu.main]]
name = "Mitmachen"
url = "/mitmachen/"
weight = 3

[[menu.main]]
name = "Ressourcen"
url = "/ressourcen/"
weight = 4

[[menu.main]]
name = "Kontakt"
url = "/kontakt/"
weight = 5

[[menu.main]]
name = "Podcast"
url = "/episode/"
weight = 6

[[menu.main]]
name = "Impressum"
url = "/impressum/"
weight = 99

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site Parameters
[params]
custom_css = ["css/custom.css"]
mainSections = ["episode"]
site_theme = "blue"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
disable_title_caps = "true"
copyright_notice = "Copyright 2025 Von der Entscheidung zur Heilung - Podcast über Abtreibungserfahrungen"
description = ""
# youtube_subscribe = "https://www.youtube.com/arresteddevops?sub_confirmation=1"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/von-der-entscheidung-zur-heilung-stimmen-nach-einer-abtreibung/id1860383572"
spotify_subscribe = "https://open.spotify.com/show/1vcZ1y2om1YxT49Naw51s0?si=UU6ZyXDMRcu7FshJeb_LjA"
rss_subscribe = "https://anchor.fm/s/10c6c7160/podcast/rss"
# pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"

# Podcast Feed Settings
[params.feed]
copyright = "Copyright 2025 Von der Entscheidung zur Heilung - Podcast über Abtreibungserfahrungen"
itunes_subtitle = "Persönliche Geschichten über Abtreibungserfahrungen"
itunes_author = "Thea Amanda Kupler"
itunes_summary = "Ein Podcast über Abtreibungserfahrungen, der Raum für persönliche Geschichten bietet. Hier erzählen Menschen von ihrer Entscheidung, ihr Kind abgetrieben zu haben, ihren Gefühlen und ihrem Weg zur Heilung."
itunes_owner_name = "Entscheidung zur Heilung"
itunes_owner_email = "entscheidung.zur.heilung@gmail.com"
itunes_top_category = "Society & Culture"
itunes_first_sub_category = "Personal Journals"
language = "de-de"

# [params.authors]
#     [params.authors.Thea]
#     name = "Thea Amanda Kupler"
#     thumbnail = "img/thea_pic.jpeg"
#     bio = ""

# Podlove Subscribe Button
# [params.podlove]
# subscribe_title = ""
# subscribe_subtitle = ""
# subscribe_description = ""
# subscribe_cover = "img/logo.jpg"
# subscribe_color = "#585e6c"
# subscribe_size = "medium"
# subscribe_format = "rectangle"
# subscribe_style = "filled"
# subscribe_language = "de"
# subscribe_feed_type = "audio"
# subscribe_feed_format = "mp3"

# Social Media Links
[params.social]
# Add your social media links here
instagram = "entscheidung.zur.heilung"
